### ISSUE TITLE
Problem while sending PATCH request

### ISSUE THREAD

**Issue by 0x111** [go-resty/resty#173]
Hi everybody!

I have a problem with sending a patch request. Below is a simple example, which if I understood correctly should work but instead it is behaving kind of weirdly.

```go
package main

import (
	"fmt"
	"gopkg.in/resty.v1"
)

func main() {
	var err error
	resty.SetDebug(true)
	resty.SetBasicAuth("rest.user", "123456")

	// Note: This is one sample of PUT method usage, refer POST for more combination

	// Request goes as JSON content type
	// No need to set auth token, error, if you have client level settings

	resp, err := resty.R().SetHeader("Content-Type", "application/json").SetBody(`{"script": "asdasdas"`).SetError(err).Patch("https://someurl")
	//
	fmt.Println("Responses: ", resp)
}

```

The code as such does not even reach the Patch part, based on my investigation it fails at the SetBody part, I tried it with a simple struct, which I've wanted to set as body which did not work either. What am I missing here?

The error message is the following:

```
panic: reflect: call of reflect.Value.Type on zero Value

goroutine 1 [running]:
reflect.Value.Type(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/lib/golang/src/reflect/value.go:1713 +0x16d
gopkg.in/resty%2ev1.getPointer(0x0, 0x0, 0x6e4c5f, 0x10)
	/home/xx/GolandProjects/src/gopkg.in/resty.v1/util.go:167 +0x86
gopkg.in/resty%2ev1.(*Request).SetError(0xc4200f2500, 0x0, 0x0, 0x6e4c5f)
	/home/xx/GolandProjects/src/gopkg.in/resty.v1/request.go:234 +0x35
main.main()
	/home/xx/GolandProjects/src/github.com/0x111/testproj/main.go:20 +0x26f
```

For reference
```
$ go version
go version go1.10.3 linux/amd64

```

**Comment by 0x111** [comment]
Nevermind. I am blind or something. Consider this solved.

**Comment by jeevatkm** [comment]
@0x111 Thank you, it seems you have figured out.
