### ISSUE TITLE
resty hangup?

### ISSUE THREAD

**Issue by chinglinwen** [go-resty/resty#194]
resty hangup? I see my start function stopped, no any output

full src is at here: https://github.com/chinglinwen/svc-d

version: gopkg.in/resty.v1 v1.9.1

```
goroutine 23 [IO wait, 2404 minutes]:
internal/poll.runtime_pollWait(0x7f613b9c8c90, 0x72, 0xc0001f3348)
	D:/soft/go/go/src/runtime/netpoll.go:173 +0x66
internal/poll.(*pollDesc).wait(0xc00026a318, 0x72, 0xffffffffffffff00, 0xe9d520, 0x14ac480)
	D:/soft/go/go/src/internal/poll/fd_poll_runtime.go:85 +0x9a
internal/poll.(*pollDesc).waitRead(0xc00026a318, 0xc000427000, 0x1000, 0x1000)
	D:/soft/go/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc00026a300, 0xc000427000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	D:/soft/go/go/src/internal/poll/fd_unix.go:169 +0x179
net.(*netFD).Read(0xc00026a300, 0xc000427000, 0x1000, 0x1000, 0x12c, 0x0, 0x0)
	D:/soft/go/go/src/net/fd_unix.go:202 +0x4f
net.(*conn).Read(0xc0002e4040, 0xc000427000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	D:/soft/go/go/src/net/net.go:177 +0x68
net/http.(*persistConn).Read(0xc000422120, 0xc000427000, 0x1000, 0x1000, 0xc00020c620, 0xc00042712a, 0x2)
	D:/soft/go/go/src/net/http/transport.go:1497 +0x75
bufio.(*Reader).fill(0xc00015ad80)
	D:/soft/go/go/src/bufio/bufio.go:100 +0x106
bufio.(*Reader).ReadSlice(0xc00015ad80, 0xa, 0x2, 0x0, 0x0, 0x1000, 0x2)
	D:/soft/go/go/src/bufio/bufio.go:341 +0x36
net/http/internal.readChunkLine(0xc00015ad80, 0x2, 0x2, 0x2, 0x2, 0x0)
	D:/soft/go/go/src/net/http/internal/chunked.go:122 +0x34
net/http/internal.(*chunkedReader).beginChunk(0xc00020c600)
	D:/soft/go/go/src/net/http/internal/chunked.go:48 +0x32
net/http/internal.(*chunkedReader).Read(0xc00020c600, 0xc000953000, 0x1000, 0x1000, 0xdcafd0, 0xc0001f36d8, 0x42ab32)
	D:/soft/go/go/src/net/http/internal/chunked.go:93 +0x125
net/http.(*body).readLocked(0xc000256000, 0xc000953000, 0x1000, 0x1000, 0x4, 0x0, 0xc0001f3778)
	D:/soft/go/go/src/net/http/transfer.go:803 +0x6c
net/http.(*body).Read(0xc000256000, 0xc000953000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	D:/soft/go/go/src/net/http/transfer.go:795 +0xde
net/http.(*bodyEOFSignal).Read(0xc000256140, 0xc000953000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	D:/soft/go/go/src/net/http/transport.go:2255 +0xd6
bufio.(*Reader).fill(0xc0002521e0)
	D:/soft/go/go/src/bufio/bufio.go:100 +0x106
bufio.(*Reader).ReadByte(0xc0002521e0, 0x0, 0x0, 0x5502bf)
	D:/soft/go/go/src/bufio/bufio.go:242 +0x39
compress/flate.(*decompressor).moreBits(0xc0000c2000, 0x0, 0x1000)
	D:/soft/go/go/src/compress/flate/inflate.go:696 +0x37
compress/flate.(*decompressor).nextBlock(0xc0000c2000)
	D:/soft/go/go/src/compress/flate/inflate.go:303 +0x36
compress/flate.(*decompressor).Read(0xc0000c2000, 0xc0009aa788, 0x29678, 0x29678, 0x2a678, 0xdc769828, 0x0)
	D:/soft/go/go/src/compress/flate/inflate.go:347 +0x77
compress/gzip.(*Reader).Read(0xc000282000, 0xc0009aa788, 0x29678, 0x29678, 0x1000, 0x0, 0x0)
	D:/soft/go/go/src/compress/gzip/gunzip.go:251 +0x87
net/http.(*gzipReader).Read(0xc00000a0a0, 0xc0009aa788, 0x29678, 0x29678, 0x1000, 0x0, 0x0)
	D:/soft/go/go/src/net/http/transport.go:2318 +0xe1
bytes.(*Buffer).ReadFrom(0xc0001bc150, 0x7f613b7e4030, 0xc00000a0a0, 0xc00000e000, 0xc88f20, 0xc7f360)
	D:/soft/go/go/src/bytes/buffer.go:206 +0xb4
io/ioutil.readAll(0x7f613b7e4030, 0xc00000a0a0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
	D:/soft/go/go/src/io/ioutil/ioutil.go:36 +0xb5
io/ioutil.ReadAll(0x7f613b7e4030, 0xc00000a0a0, 0xc00000a0a0, 0x7f613b7e4030, 0xc00000a0a0, 0x80, 0x4e)
	D:/soft/go/go/src/io/ioutil/ioutil.go:45 +0x3e
gopkg.in/resty%2ev1.(*Client).execute(0xc000078600, 0xc000100000, 0x0, 0x0, 0x0)
	D:/gocode/pkg/mod/gopkg.in/resty.v1@v1.9.1/client.go:824 +0x57e
gopkg.in/resty%2ev1.(*Request).Execute.func1(0xc0003060c0, 0x151b698, 0xc0004d8380)
	D:/gocode/pkg/mod/gopkg.in/resty.v1@v1.9.1/request.go:480 +0xcf
gopkg.in/resty%2ev1.Backoff(0xc0001f3db8, 0xc0001f3d98, 0x4, 0x4, 0xc0000d00f0, 0x44)
	D:/gocode/pkg/mod/gopkg.in/resty.v1@v1.9.1/retry.go:85 +0x27d
gopkg.in/resty%2ev1.(*Request).Execute(0xc000100000, 0xd8fd0e, 0x3, 0xc0000d00f0, 0x44, 0x40d05d, 0xd52e00, 0xc000306090)
	D:/gocode/pkg/mod/gopkg.in/resty.v1@v1.9.1/request.go:474 +0x368
gopkg.in/resty%2ev1.(*Request).Get(0xc000100000, 0xc0000d00f0, 0x44, 0x6f434f, 0xc0001f3eb8, 0x40c488)
	D:/gocode/pkg/mod/gopkg.in/resty.v1@v1.9.1/request.go:413 +0x54
wen/svc-d/check.Fetchs(0xc0a2e0, 0x151b698, 0xc00015c040, 0x2, 0x2)
	D:/gocode/src/wen/svc-d/check/fetch.go:158 +0x18c
wen/svc-d/check.Start(0xc00012c380)
	D:/gocode/src/wen/svc-d/check/check.go:47 +0x295
created by main.main
	D:/gocode/src/wen/svc-d/main.go:92 +0x21b
```

full stack here: https://pastebin.com/Lkdpwj6d

**Comment by chinglinwen** [comment]
last log:

```
2018/10/10 19:14:11 starting fetch at Wed Oct 10 19:14:11 CST 2018, last time elapsed 10.000246608s
2018/10/10 19:14:11 got 637 projects, 2 enabled, 2 is docker, 2 to be check
2018/10/10 19:14:11 fetch ok
checked 0, bank_depository_admin#qb-pre#tcp 10.64.193.134:8080, ok
checked 1, ops_test#qb-pre#http http://10.64.193.132:8090/, ok
2018/10/10 19:14:16 all checks done  
2018/10/10 19:14:16 background check ok
2018/10/10 19:14:16 going sleep for 4.65920112s

2018/10/10 19:14:21 starting fetch at Wed Oct 10 19:14:21 CST 2018, last time elapsed 10.00015009s
2018/10/12 11:17:23 started gops
2018/10/12 11:17:23 got signal, set log level to  debug
```

**Comment by jeevatkm** [comment]
@chinglinwen Use resty debug log to analyze the issue. `resty.SetDebug(true)`.

**Comment by chinglinwen** [comment]
It can't  set debug, since it's already running, it just happen sometimes, I have no idea how to reproduce it. @jeevatkm

**Comment by chinglinwen** [comment]
I have try simulate network error, it can handle as expect though

```
2018/10/12 14:09:54 starting fetch at Fri Oct 12 14:09:54 CST 2018, last time elapsed 10.000076852s
RESTY 2018/10/12 14:10:24 ERROR Get http://upstream-test.sched.qianbao-inc.com:8010/get_upstream_all_instance/: dial tcp 172.28.40.76:8010: i/o timeout, Attempt 1
RESTY 2018/10/12 14:10:55 ERROR Get http://upstream-test.sched.qianbao-inc.com:8010/get_upstream_all_instance/: dial tcp 172.28.40.76:8010: i/o timeout, Attempt 2
RESTY 2018/10/12 14:11:25 ERROR Get http://upstream-test.sched.qianbao-inc.com:8010/get_upstream_all_instance/: dial tcp 172.28.40.76:8010: i/o timeout, Attempt 3
2018/10/12 14:11:25 fetch upstream error Get http://upstream-test.sched.qianbao-inc.com:8010/get_upstream_all_instance/: dial tcp 172.28.40.76:8010: i/o timeout
2018/10/12 14:11:25 starting fetch at Fri Oct 12 14:11:25 CST 2018, last time elapsed 1m40.481455781s
RESTY 2018/10/12 14:11:55 ERROR Get http://upstream-test.sched.qianbao-inc.com:8010/get_upstream_all_instance/: dial tcp 172.28.40.76:8010: i/o timeout, Attempt 1
RESTY 2018/10/12 14:12:25 ERROR Get http://upstream-test.sched.qianbao-inc.com:8010/get_upstream_all_instance/: dial tcp 172.28.40.76:8010: i/o timeout, Attempt 2
2018/10/12 14:12:28 got 20 projects, 0 enabled, 0 is docker, 0 to be check
2018/10/12 14:12:28 fetch ok
2018/10/12 14:12:28 all checks done  
2018/10/12 14:12:28 background check ok
2018/10/12 14:12:28 going sleep for -53.356203897s
```

**Comment by chinglinwen** [comment]
Hi, the normal request debug info similar to the following.

```
RESTY 2018/10/15 11:39:37 
---------------------- REQUEST LOG -----------------------
GET  /get_upstream_all_instance/  HTTP/1.1
HOST   : upstream-pre.sched.example.com
HEADERS:
               User-Agent: go-resty/1.9.1 (https://github.com/go-resty/resty)
BODY   :
***** NO CONTENT *****
----------------------------------------------------------
RESTY 2018/10/15 11:39:37 
---------------------- RESPONSE LOG -----------------------
STATUS 		: 200 OK
RECEIVED AT	: 2018-10-15T11:39:37.107821285+08:00
RESPONSE TIME	: 107.40787ms
HEADERS:
               Connection: keep-alive
             Content-Type: application/json
                     Date: Mon, 15 Oct 2018 03:39:37 GMT
                   Server: Tengine
                     Vary: Accept-Encoding
BODY   :
[
   {
      "enabled": "1",
      "env": "pre",
      "idc": "BJ-M7",
      "ip": "10.64.160.21",
      "is_docker": "0",
      "namespace": "",
      "port": "8080",
      "project": "pay_security_ppms"
   },
   {
      "enabled": "1",
      "env": "pro",
      "idc": "BJ-SH",
      "ip": "10.19.37.75",
      "is_docker": "0",
      "namespace": "",
      "port": "8080",
      "project": "pay_security_ppms"
   },
...
```

I have changed the code from direct use of R to create a my own client, it seems not happening again, don't know whether the problem gone or not.

For three days, no hang up been found.

**Comment by jeevatkm** [comment]
@chinglinwen Thanks for sharing updates. FYI `R()` func returns new request object that uses global default resty client.

**Comment by chinglinwen** [comment]
I don't see it happen again, no idea (may fixed by code change).

**Comment by jeevatkm** [comment]
Okay, Thanks for the updates. I'm closing this one.
