### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by draveness** [go-resty/resty#592]
```
panic: runtime error: slice bounds out of range [524288:266754]

goroutine 1470 [running]:
bytes.(*Buffer).Bytes(...)
	/opt/hostedtoolcache/go/1.19.1/x64/src/bytes/buffer.go:54
net/http.NewRequestWithContext({0xca59f0?, 0xc00003e0a0}, {0xb796a9?, 0xc002547a00?}, {0xc002052630?, 0xa1?}, {0xc9eda0, 0xc00097f4a0?})
	/opt/hostedtoolcache/go/1.19.1/x64/src/net/http/request.go:899 +0x7f1
net/http.NewRequest(...)
	/opt/hostedtoolcache/go/1.19.1/x64/src/net/http/request.go:836
github.com/go-resty/resty/v2.createHTTPRequest(0xc000342000, 0xc002547a00)
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/middleware.go:175 +0x71
github.com/go-resty/resty/v2.(*Client).execute(0xc000342000, 0xc002547a00)
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/client.go:909 +0x1a2
github.com/go-resty/resty/v2.(*Request).Execute(0xc002547a00, {0xb796a9?, 0x0?}, {0xc0055a4900, 0x15})
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:758 +0x5e9
github.com/go-resty/resty/v2.(*Request).Post(...)
	/home/runner/go/pkg/mod/github.com/go-resty/resty/v2@v2.7.0/request.go:699
```

```go
					klog.Infof("start to upload object, date=%s path=%s", date, partition.Path)

					if err := retry.Do(func() error {
						resp, err := client.
							R().
							SetQueryParams(map[string]string{
								"zone":       c.Zone,
								"date":       date,
								"instrument": partition.Instrument,
								"type":       partition.Type,
								"index":      fmt.Sprint(partition.Index),
							}).
							SetFile("file", partition.Path).
							Post(fmt.Sprintf("/v1/datastore/objects"))
						if err != nil {
							return errors.Wrapf(err, "unable to upload objects")
						}

						if resp.StatusCode() != 200 {
							return fmt.Errorf("unable to upload objects, body=%s", resp.Body())
						}

						return nil
```

The above code panic when post files to server, can I use the same client in a different goroutine or do I have to create a client pool?

**Comment by jeevatkm** [comment]
@draveness Typically, you can use clients in multiple goroutines to raise requests. However, do not modify the client settings on different goroutines.
Ideally, I recommend you create a client per host URL.
